---
title: "Untitled"
author: "Willem"
date: "13 March 2019"
output: pdf_document
---
```{r packages, echo=F, warnings=F, message=F, eval=T}
require(knitr)
require(kableExtra)
```

Try out the table

```{r summarytable, echo=F, message=F, eval=T}

table <- as.data.frame(matrix(c("LC variable","Small area of significant pixels in the centre","Large area possibly aligning with bushfire affected area.",
"t-test regression model residuals","Slightly lower mean residual ($p<0.05$) after change (0.5 mm per month)","Lower mean residual ($p<0.05$) after change (1.5 mm per month)",
"Positive score","0.2\\% of pixels at $p<0.1$","3.7\\% of pixel at $p<0.1$",
"Field significance \\% of scores", "Both positive and negative \\% within random distribution", "Positive \\% outside random distribution."
),nrow=4,ncol=3, byrow=T))
kable(table,caption="Summary table of all tests on the two regions ", 'latex',
      booktabs =TRUE, escape=F,col.names = c("Test","Qld" ,"NSW VIC")) %>%
column_spec(2:3, width = "7cm") %>%
  kable_styling(latex_options = "scale_down")#%>%
  #kableExtra::landscape()
```
